### ISSUE TITLE
 the second curl not feedback transaction id

### ISSUE THREAD

**Issue by wangmarkqi** [khanhnb/fabric-ca-go#1]
curl -s -X POST \
  http://localhost:4000/channels/mychannel/chaincodes/mycc \
  -H "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTQ4NjU1OTEsInVzZXJuYW1lIjoiSmltIiwib3JnTmFtZSI6Im9yZzEiLCJpYXQiOjE0OTQ4NjE5OTF9.yWaJhFDuTvMQRaZIqg20Is5t-JJ_1BP58yrNLOKxtNI" \
  -H "content-type: application/json" \
  -d '{
	"peers": ["peer0.org2.example.com","peer1.org2.example.com"],
	"fcn":"invoke",
	"args":["a","b","10"]
}'
i did the steps according to tutorial but the above curl not feet back transaction id and the rest of curl failed too. i did change auth token based on first curl.

**Comment by khanhnb** [comment]
@wangmarkqi : Thanks for reporting this error. I forgot to replace fixed authorization token. Actually, you should replace this part
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTQ4NjU1OTEsInVzZXJuYW1lIjoiSmltIiwib3JnTmFtZSI6Im9yZzEiLCJpYXQiOjE0OTQ4NjE5OTF9.yWaJhFDuTvMQRaZIqg20Is5t-JJ_1BP58yrNLOKxtNI
```
with the output token from the first request aka Login request.
